/**
 * Created by Ergardt.Vladimir on 27.02.2019
 */

export const PASS_IS_READY = 'PASS_IS_READY'
export const PASS_IS_NOT_READY = 'PASS_IS_NOT_READY'
export const SET_PREVIOUS_PAGE = 'SET_PREVIOUS_PAGE'
export const SET_ORGANIZATIONS = 'SET_ORGANIZATIONS'
export const SET_ORGANIZATIONS_ALPHABET = 'SET_ORGANIZATIONS_ALPHABET'
export const SET_CURRENT_ORGANIZATION = 'SET_CURRENT_ORGANIZATION'
